main:
    resource: "@ABBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# Point FOS profile to AB profile
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_profile_show:
#    pattern: /profile
#    defaults: { _controller: RefreshingAppBundle:Profile:view }
#fos_user_profile_edit:
#    pattern: /profile/edit
#    defaults: { _controller: RefreshingAppBundle:Profile:edit }

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

linkedin_login:
    pattern: /loginOAuth/check-linkedin

login_check:
    path:   /login_check

logout:
    path:   /logout


login_check:
    path:   /login_check

logout:
    path:   /logout
