security:
    encoders:
        AB\Bundle\Entity\User:
            algorithm:        pbkdf2
            hash_algorithm:   sha512
            encode_as_base64: true
            iterations:       1000

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_PUPIL, ROLE_MENTOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        participants:
            entity: { class ABBundle:User:, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login: ~
            logout:     ~

    access_control:
